### PR TITLE
Add Pug

### PR DESCRIPTION
**Pull request by stealthybox**
- Addresses #231

### CODE REVIEW

**Comment by stealthybox** [comment]
@ForbesLindesay: Hopefully this fits in with your new `pug` npm packages.

**Comment by BridgeAR** [comment]
@stealthybox would you be so kind and use the existing code and implement pug into that and squash your commits afterwards?

Otherwise LGTM

**Comment by stealthybox** [comment]
@BridgeAR I think you're referring to the first commit, where I duped the Jade functions in lib/consolidate to get Pug running.

The only way I can think of to reduce the code is to declare two functions that parameterize the name used in the require statements for the jade and pug exports.
I don't see an example of another module doing that though.

Jade and Pug are different repos, so it may be a good idea to keep these functions separate.
The projects will diverge which may necessitate independent changes.

I think there still need to be individual test files and readme entries?
I'm new to the codebase, so LMK if you can think of a good way to structure this!

**Comment by doowb** [comment]
Merged thanks @stealthybox. Sorry it took so long to get to.

**Comment by stealthybox** [comment]
no problem @doowb
:+1: 

thanks everyone!

**Pull request merged**
