### PR TITLE
Added Express-Vue

### PR DESCRIPTION
**Pull request by danmademe**
Added support for express-vue.

Server side rendered Vue.js library using express, more information on express-vue and vue.js can be found on these links.

https://github.com/danmademe/express-vue
https://vuejs.org

A working example of express-vue and consolidate.js can be found on the master branch of my fork
https://github.com/danmademe/consolidate.js

### CODE REVIEW

**Comment by danmademe** [comment]
i think consolidate.js is dead.. #275 discusses it.

if its alive cool beans.. ill bump this pull request

**Comment by bonesoul** [comment]
any alternatives? @danmademe 
I'd like to both use server-side with your https://github.com/danmademe/express-vue and nunjucks, is that even possible?

**Comment by danmademe** [comment]
@bonesoul I don't know if it is or isn't possible, but i would seriously advise against that... what express-vue is, is an integration between express and vue.js, so you can use vue.js as a tempting engine.. really don't know why you would bother with nunjucks, when Vue is so much better at literally everything..

**Comment by bonesoul** [comment]
@danmademe I've have an huge existing app already and it'll take some time before i can port it but with express-vue, it would like to give vue as a try as a start.

**Comment by danmademe** [comment]
you can do that, go client side, then when you've got enough ported, you can easly migrate from client side vue to my server side method

**Comment by snewell92** [comment]
I just tried using the aformentioned fork, but [this bug](https://github.com/express-vue/express-vue/issues/59) still persists for me.

This line looks backward : line 14 of `defaults.js`

```
this.rootPath =
  options.settings.vue.rootPath === undefined
    ? options.settings.views + '/'
    : options.settings.vue.rootPath;

```

**Comment by danmademe** [comment]
Like I said. That change is in master right now. I'll have to debug this more. Alternatively. You are able to add consolelogs into the code in your npm_modules and restart the node server and it will log objects.

**Comment by doowb** [comment]
I've been working on merging in PRs.

@danmademe if you'd still like this included, please add a test.

**Comment by danmademe** [comment]
Well it's been a long long time since i opened this PR.

There's no reason to be in this, 2 things have happened since then

1. Sails moved away from using this package
2. I re-wrote it as middleware ditching res.render since its sync and slow

**Comment by akhoury** [comment]
@danmademe I added vue support using your vue-pronto module, see this PR https://github.com/tj/consolidate.js/pull/315

**Comment by akhoury** [comment]
@danmademe I just wished there is a better way vue-pronto can

### 1) turn off cache completely

### 2) just render a template literal with a data hash, see what i did here: 
https://github.com/tj/consolidate.js/blob/78de9e8426e2bd8bd30ceaf4ad800851b89c24dc/lib/consolidate.js#L1772-L1801

### 3) just accept in a fullpath of a file and get it to work
the `rootPath` thing isn't working for me, I think you should use `process.cwd()`instead of `__dirname` [here](https://github.com/express-vue/vue-pronto/blob/81f45ab49add61fa62c576e3a199784d8690da18/lib/utils/findPaths.js#L12)
```javascript
        const currentPath = path.resolve(__dirname);
```
see my rootPath workarounds here: https://github.com/tj/consolidate.js/blob/78de9e8426e2bd8bd30ceaf4ad800851b89c24dc/lib/consolidate.js#L1725-L1751


Sorry let's discuss these there...

**Pull request closed without merging**
