### PR TITLE
use swig-templates module

### PR DESCRIPTION
**Pull request by fatihky**
since swig module is unmaintained, there is a maintained fork exists.

### CODE REVIEW

**Comment by doowb** [comment]
@fatihky thanks for the PR.

Can you change this so both options are available and the user can decide which one they want to use? This will be similar to `jade` and `pug` that try to require in `pug` and if that fails, then requires in `then-pug`.

Then you can include the `swig-templates` link in the readme after the unmaintained `swig` link.

**Comment by fatihky** [comment]
Hey @doowb, I made changes prior to your comment. Could you check them out if these ok?

**Comment by doowb** [comment]
@fatihky this looks great, thanks!

**Comment by fatihky** [comment]
thank you @doowb!

**Pull request merged**
