### PR TITLE
Add support for Promises

### PR DESCRIPTION
**Pull request by alexsomeoddpilot**
If no callback `fn` is provided, render functions should return Promises which either resolve to the compiled HTML or an error.

No changes are made to the regular API, only the addition of the return value when no callback is provided.

### CODE REVIEW

**Comment by doowb** [comment]
@alexsomeoddpilot this looks great!

Since you're adding a promise library dependency, I'd prefer to use [bluebird](https://github.com/petkaantonov/bluebird). When that's updated, I'll test it out and merge it in.

Thanks.

**Comment by alexsomeoddpilot** [comment]
No problem! I've switched to using bluebird with a couple of lines in 8d6a10b and the tests should stay the same.

**Comment by doowb** [comment]
:+1: looks good.

**Comment by doowb** [comment]
This has been released in `0.13.0`.

**Comment by alexsomeoddpilot** [comment]
Thanks! I'll work on writing up some usage of the promise API in the readme.

**Pull request merged**
