### PR TITLE
Add ARC Template support

### PR DESCRIPTION
**Pull request by StephenCleary**
ARC templates are described here: https://github.com/StephenCleary/arc-templates

### CODE REVIEW

**Comment by StephenCleary** [comment]
ARC templates require a Node.js version 4, and it appears your CI is using an older version.

**Comment by StephenCleary** [comment]
I changed ARC Templates to support older versions of Node.js.

**Comment by BridgeAR** [comment]
LGTM please rebase

**Comment by doowb** [comment]
Merged in, thanks @StephenCleary

**Pull request merged**
