### PR TITLE
resolve paths

### PR DESCRIPTION
**Pull request by cameronjroe**

### CODE REVIEW

**Comment by cameronjroe** [comment]
Would love to have this merged. :)

**Comment by BridgeAR** [comment]
Superseded by #215 as it also included a test case.

Please also include a description in future. Not everyone looking at the PR might be familiar with the code base.

**Comment by cameronjroe** [comment]
Sure, but that doesn't resolve the path, it's just tweaking `path.basename`

**Comment by BridgeAR** [comment]
You're right, I'm sorry. I just had a glimpse. But this needs a rebase and a slightly different approach to also work with the extension.
It should be:
```js
        var extname = path.extname(name) ? '' : '.liquid';
        var filename = path.resolve(includeDir, name + extname);
```
So please feel free to reopen and to rebase.

**Comment by cameronjroe** [comment]
Wouldn't that add replace with an empty string if the extension is found? It should be

`var extname = path.extname(name) || '.liquid';`

**Comment by BridgeAR** [comment]
If the extension is found it'll double the extension that way. But just go ahead and add and run the tests :)

**Pull request closed without merging**
