### PR TITLE
added vue support

### PR DESCRIPTION
**Pull request by akhoury**
There is a temporary dependency from a github fork instead of a published npm module,
the [PR](https://github.com/express-vue/vue-pronto/pull/67) has been approved, just waiting for it to be published.

### CODE REVIEW

**Comment by doowb** [comment]
@akhoury thanks for the PR. I'll try to get this reviewed soon.

> There is a temporary dependency from a github fork instead of a published npm module,
the PR has been approved, just waiting for it to be published.

Thanks for this information, it'll probably be better to wait until the other PR is published.

**Comment by tmasrat** [comment]
@akhoury @doowb what is the status on this? It would help me a lot on the project I am working on. 
Thanks!

**Comment by akhoury** [comment]
@doowb I removed the github fork dependency so it's now using a published version of the vue-pronto module, but not the latest one because of some of their breaking changes.

but it's not still not working in Node 4 :/ not sure how hard of a requirement that is

**Comment by akhoury** [comment]
@tmasrat if you absolutely needs this and can't wait for this PR to be merged and published, in your `package.json` you can point `consolidate.js` dependency to use my github fork with a specific commit hash so you wont to use `master` and risk breaking anything every time i make a change
 
```json

    "consolidate.js": "github:akhoury/consolidate.js#7c1ffce0c68aa85c41f490c4eafe8b3d62a3e72c",
```

**Comment by tmasrat** [comment]
@akhoury thanks! I will explore other options but if it comes down to it, I will use your fork.

**Comment by simllll** [comment]
Also looking forward to this. Many libraries have dropped node <6 support already, in my opinion it would be okay to go for that here too.

**Comment by ITernovtsiy** [comment]
@doowb any chance this will be merged soon?

**Comment by niftylettuce** [comment]
Fix conflicts and ping me back

**Comment by niftylettuce** [comment]
(and resubmit a new PR)

**Pull request closed without merging**
