### PR TITLE
Add support for Marko

### PR DESCRIPTION
**Pull request by fabsrc**
Support for Marko as requested in #235.

### CODE REVIEW

**Comment by jdnichollsc** [comment]
Any update about that? :+1:

**Comment by philidem** [comment]
This change looks good. Thanks @fabsrc for submitting.

Can this be merged?

**Comment by niftylettuce** [comment]
can you please update to the latest and push again? see v.0.14.2

**Comment by fabsrc** [comment]
OK, done. Should be mergeable now.

**Comment by niftylettuce** [comment]
Thank you @fabsrc

**Comment by niftylettuce** [comment]
@fabsrc @jdnichollsc @philidem please see the newly released version `0.14.4` in NPM, `npm install consolidate@latest`.

**Pull request merged**
