### PR TITLE
Improve "Supported template engines" in README.md

### PR DESCRIPTION
**Pull request by A-312**
I made this table for my npm package. (I think it can interest you)

### CODE REVIEW

**Comment by doowb** [comment]
This looks great. I just merged in another PR that caused this to be conflicted. Will you update the table with the new update?

**Comment by A-312** [comment]
I'll do, ping me when I can

**Comment by A-312** [comment]
I tried this:

image

But, I think there is too many images.

**Comment by A-312** [comment]
@doowb My PR is ready

**Comment by A-312** [comment]
@doowb This PR is ready

**Comment by A-312** [comment]
@doowb Hi, this PR is ready , are you waiting something ?

**Comment by doowb** [comment]
> are you waiting for something

No, thanks for the ping, I've just been busy. I'll take a look this weekend.

**Comment by A-312** [comment]
@doowb You forgot it 😜

**Comment by doowb** [comment]
Thanks for the reminder... again ;)

**Comment by nebrelbug** [comment]
Hey @doowb and @A-312, it looks like when you created the new table you left out Squirrelly, which had just gotten added in #317.

Should I make a pull request to add it?
Thanks!

**Comment by doowb** [comment]
> Should I make a pull request to add it?

Yes please! Sorry for overlooking it when merging.

**Comment by A-312** [comment]
@nebrelbug Sorry ! I make a mistake in my rebase :(

**Comment by nebrelbug** [comment]
@A-312 @doowb just created the pull request! See #326 😄

**Pull request merged**
