### PR TITLE
Added support for React JS templates

### PR DESCRIPTION
**Pull request by yeojz**
Added support for React JS as template, but unsure if it is in line with other template engines that consolidate.js supports since it differs slightly.

Note: Test cases for React removes caching tests since it uses `require` rather than `fs.readFile`, and as such, those 2 test cases do not apply.

### CODE REVIEW

**Comment by doowb** [comment]
I really like this code, but some of the options/methods seem to stray from what consolidate does. It might be okay in this case, but I'd like to get feedback from some other people watching this repository before merging it in.

The only concerns that I have are:

 - Adding the `jsx` extension to `require`
 - `base` option allowing the "naive" templates

I'm okay with the `jsx` extension because you're only adding it if it's not already added and only if `react` is used.

I'm on the fence about the `base` option because this is adding additional functionality that React doesn't have natively. I'm not finding an example of something like this with other engines in consolidate and that's the only reason why I have a concern.

I'll give this a couple of days and if anyone else any comments/concerns please let me know. Otherwise, I think this is a great PR and will merge in it.

**Comment by yeojz** [comment]
Yes, I do agree that it strays a little from `consolidate.js` due to the way `React` works.

Noted on the `base` option. It only made it in because it seems  a little weird having to run it through consolidate.js twice if I want to insert the content into the container file (like how `React` works in a fully client side rendering scenario). I would say it's like having a simplistic `React.render` function.

But am totally fine with taking it out if we want to keep strictly to the `React` feature set though.

**Comment by coodoo** [comment]
Would really love to see this PR got merged ASAP, thanks!

**Comment by doowb** [comment]
released in `0.12.0`

**Comment by coodoo** [comment]
Woohoo, thanks!

Btw, the `base` option is very practical to react's use case, by providing a html I could put everything else needed in there, see the example I built here:
https://github.com/coodoo/koa-react-views

**Pull request merged**
