### PR TITLE
add Contemplate engine support

### PR DESCRIPTION
**Pull request by foo123**
as requested, added support for [Contemplate](https://github.com/foo123/Contemplate) to consolidate.js and create a pull request

### CODE REVIEW

**Comment by doowb** [comment]
I'm not finding `Contemplate` on npm. It looks like you have builds for javascript but nothing published on npm. If you add that and update the `require` for the actual npm repo and add tests, this can be merged.

Right now, the setup seems too complicated to include in consolidate.

**Comment by foo123** [comment]
Hi thanks

True there is no npm package for Contemplate engine (nor for any other node/js packages that i currently have)

However Contemplate can just be required inside a node script and it will work just fine (or even be put in the global path)

i'm not sure i want to add an npm package for this (personaly i try to make modules standalone and use as needed, if needed)

If that is a problem, it;s ok, thanks anyway

**Comment by BridgeAR** [comment]
Please publish the library on npm or close the pr as I'd only include it if it's published on npm.

Besides that tests are missing.

**Comment by foo123** [comment]
ok, i dont plan put the engine on npm

Thanks

**Pull request closed without merging**
